src/libumockdev-preload.c
src/posix_extra.vapi
tests/test-umockdev.c

These funcs are defined in the sys/sysmacros.h header, not sys/types.h.
Linux C libraries are updating to drop the implicit include, so we need
to include it explicitly.

include sys/sysmacros.h for major/minor/makedev

---

src/umockdev-record.vala
src/umockdev-run.vala

Fixes:
src/umockdev-run.vala:35.1-54.2: warning: the modifier `static' is not applicable to constants
src/umockdev-record.vala:352.1-363.2: warning: the modifier `static' is not applicable to constants

Don't declare constants as static

---

src/umockdev.vala

umockdev-run itself sets $LD_PRELOAD, so this does not avoid the error
message about nonexisting devices in uevent_sender_send(). Instead,
check if /sys looks like a real file system directory, i. e. it is a
mock, not the real sysfs.

Refine detection of being in mock environment

---

src/umockdev.vala

This should create /sys/bus/thunderbolt and links.

thunderbolt: Create symlinks the same way like usb and pci

---

src/umockdev.vala

Fixes symlinks not removed during remove_device()
Sorry missed this part in the previous patch.

thunderbolt: Remove symlinks

---

src/uevent_sender.c
tests/test-umockdev.c

action, devpath, and other values are unbounded, so ensure that we don't
overflow the property buffer. This does not cross a security boundary
and is not typically used with untrusted data, so not really a
vulnerability. But show a proper error message instead of crashing if it
happens.
Thanks to Simon Schmitt <symenschmitt@web.de> for pointing this out!

Avoid buffer overflow in uevent_sender_send()

---

.travis.yml
tests/run-ubuntu-chroot

Ubuntu 14.04 is becoming too old, and misses changes and breakage from
newer system libraries, like issue #69.
Move to building and testing in Launchpad buildd chroots for a given
Ubuntu release and architecture. Add Travis configuration to use this
for the current LTS, the current stable, and the current devel series.

Run tests on multiple Ubuntu releases

---

tests/test-umockdev.c

`/proc/cpuinfo` is very architecture specific and has no reliable
strings in it. Use `/proc/meminfo` instead.
Thanks to John Paul Adrian Glaubitz!
Fixes #73

Fix architecture specific /proc test

---

README.rst

As described in the man page two minuses indicate that argument parsing
should stop there.
Signed-off-by: Bastian Krause <basti@randomprojects.de>

README: fix umockdev-run call

---

src/umockdev.vala

This isn't true for tmpfs, which leads to hard to debug errors.

Don't expect size to be non-zero for mocked /sys

---

src/umockdev.vala
tests/test-umockdev.c

This adds a lookup matching function to match all (current) bus names
isntead of just 3 names.

Add all bus names from Linux kernel 5.3

---

src/libumockdev-preload.c

If finding one of the symbols for a function fails, whichever function
it is, we'd get this error message:
```
python3: src/libumockdev-preload.c:81: get_libc_func: Assertion `fp' failed.
```
Update the code to throw an error on stderr before failing, for example:
```
umockdev: could not get libc function __xstat64
```

preload: Better debug for functions missing from libc

---

tests/test-static-code

Those warnings a printed on stderr since the new grep 3.5 version,
which fails the Debian autopkgtest
From the grep NEWS
```
Noteworthy changes in release 3.5 (2020-09-27) [stable]
** Changes in behavior
The message that a binary file matches is now sent to standard error
and the message has been reworded from "Binary file FOO matches" to
"grep: FOO: binary file matches", to avoid confusion with ordinary
output or when file names contain spaces and the like, and to be
more consistent with other diagnostics.  For example, commands
like 'grep PATTERN FILE | wc' no longer add 1 to the count of
matching text lines due to the presence of the message.  Like other
stderr messages, the message is now omitted if the --no-messages
(-s) option is given.
```

Don't display grep 'binary file matches' errors

---

src/umockdev-record.vala

I am trying to create some tests for thermald, and it is accessing the
firmware_node. As such, it is helpful to store the information in the
recording.

record: Do not filter out firmware_node

---

src/libumockdev-preload.c

The `"/proc/"` string is of len 6 instead of 5.
This was found with a "cstrnfinder" research and I haven't tested this change (more info https://twitter.com/disconnect3d_pl/status/1339757359896408065). Close this PR if this change is incorrect.

Fix strncmp off-by-one in libumockdev-preload.c

---

src/umockdev.vala

Otherwise we may end up selecting an FD that does not exist, detecting
EOF and the thread quits immediately. This causes random failures of the
test suite.
A sample of a failure caused by this can be seen in https://github.com/martinpitt/umockdev/runs/2730392818?check_suite_focus=true#step:3:2025
FD is 0 here, but should obviously be non-zero.
EDIT: Update link; for some reason it ended up pointing to the later run.

umockdev: Only start socket server thread after creating FDs

---

src/libumockdev-preload.c
src/umockdev-pcap.vala

When the end of recording is reached, we might try to access URB
information that did not exist. Simply return immediately instead of
going on to fix this.

pcap: Fix crash after reaching end of recording

---

docs/reference/meson.build
docs/reference/umockdev-docs.xml
docs/reference/umockdev-sections.txt
src/libumockdev-preload.c
src/umockdev-ioctl.vala
src/umockdev-pcap.vala
src/umockdev-record.vala
src/umockdev-spi.vala
src/umockdev.vala
tests/test-umockdev-vala.vala

On top of #125 (sorry, but need fixes from there to make sense).
API is not optimal yet:
* We could remove the main context from the `IoctlBase` initialisation, then pass it when attaching the device
* Then we can hide it completely (or at least provide a good default)
* detach requires passing the handler again; we could just hide that behind a hash table for lookup
But, works nicely.

Public ioctl api

---

tests/test-umockdev-record.vala

Commit e4ea3a7198 introduced a very strict comparison. But in different
build environment (such as Debian experimental buildds) this ends up as
5 instead of 133, as the 0x80 signal mask is not present for some
reason.
The precise value is not important, we just want to make sure it fails,
so relax the check.
-----
This should fix the [debian experimental failure](https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=amd64&ver=0.16.0-1&stamp=1625132699&raw=0). It failed on [almost all architectures](https://buildd.debian.org/status/package.php?p=umockdev&suite=experimental). I can't reproduce this locally in a Debian experimental container.

test: Relax exit code comparison in /umockdev-record/script-log-append-dev-mismatch

---

src/ioctl.vapi

Including ioctl.h from asm-generic is not correct, as it will pick up
the wrong constants on some architectures. As such, include asm/ioctl.h
to avoid randomly overriding the values of some constants.
This fixes ppc64le.

ioctl: Fix ioctl.h include location

---

docs/reference/meson.build
docs/reference/umockdev-docs.xml

umockdev doesn't export any GObject object types, so gtk-doc should not
be trying to create an empty types file, or including an object class
tree in its documentation.
See https://gitlab.gnome.org/GNOME/gtk-doc/issues/48
See https://github.com/mesonbuild/meson/issues/3892
See https://bugzilla.redhat.com/show_bug.cgi?id=1604585

docs: Remove types handling from docs

---

src/umockdev.vala
tests/test-umockdev-vala.vala
tests/test-umockdev.c

libudev expects the "/sys/bus" and "/sys/class" directories to exist when calling `udev_enumerate_scan_devices()`. When this was called on an empty `Testbed`, it would return `-ENOENT` since these directories did not exist.
This fixes the issue by creating the "/sys/bus" and "/sys/class" at the same time that "/sys" is created in the `Testbed`.
`num_udev_devices()` is modified to call `udev_enumerate_scan_devices()` directly instead of using GUdev, which ignores the return value of `udev_enumerate_scan_devices()`. This makes `t_testbed_empty()` a valid test for the bug we are fixing.
Some vala tests also had to be modified to account for the change.
Fixes: https://github.com/martinpitt/umockdev/issues/144

Testbed: Create "bus" and "class" dirs at init

---

src/umockdev.vala
tests/test-umockdev-run.vala

Commit 1b58d24fb78e regressed these, as it included the trailing \n into
the dev symlinks, like
'7:23'$'\n' -> ../../devices/virtual/block/loop23
Strip off whitespace from the recorded `dev` attribute to fix this.
Fixes #155

Fix /sys/dev/* symlinks

---

src/umockdev-spi.vala
tests/test-umockdev-vala.vala

Adjust commit 0da63a9259: Turns out that HIDIOCGRDESCSIZE is generally
broken on big-endian machines, it fails the same way on real-iron s390x
and also ppc64.
---
[ubuntu s390x failure](https://launchpadlibrarian.net/579523463/buildlog_ubuntu-jammy-s390x.umockdev_0.17.2-1_BUILDING.txt.gz), [Debian ppc64 failure](https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=ppc64&ver=0.17.2-1&stamp=1641805816&raw=0), [Debian s390x failure](https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=s390x&ver=0.17.2-1&stamp=1641804671&raw=0)

test: Don't check HIDIOCGRDESCSIZE result on big-endian machines

---

src/uevent_sender.c
src/uevent_sender.h
src/uevent_sender.vapi
src/umockdev.vala
tests/test-umockdev.c
tests/test-umockdev.py

Current systemd by and large does not read the /uevent file any more,
but entirely relies on udevd sending the properties in the udev netlink
events.
Pass the properties to uevent_sender_send(), massage them from a
newline separated (as in our uevent file) to a nul separated (as
expected by the udev netlink message) array. In Testbed.uevent(), read
the current properties from the /uevent file.
This is all rather hackish right now and cries for a more thorough
rewrite. But this is a relatively unintrusive and quick bandaid which
helps users for the time being.
Test this both with the libudev and with the gudev (through Python) APIs.
Fixes #164

Include udev properties in emulated netlink messages

---

meson.build

As per:
```
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300
```

build: Check whether run_command() succeeded

---

src/uevent_sender.c
tests/test-umockdev.c

Some tests need more than 1 KiB of property data.
Fixes #167

uevent_sender: Increase buffer size

---

tests/test-umockdev-vala.vala

This also fails in some riscv64 builds (not in Debian's or Ubuntu's,
though). This failure is hard to reproduce, it even passes with
sudo systemd-run -p CPUQuota=1% -dt --wait sh -ec 'LD_LIBRARY_PATH=. LD_PRELOAD=libumockdev-preload.so ./test-umockdev-vala -p /umockdev-testbed-vala/detects_running_outside_testbed'
So mark it as brittle for now to skip it in normal package builds.
Fixes #169

Mark /umockdev-testbed-vala/detects_running_outside_testbed as brittle

---

src/libumockdev-preload.c

Implement wrapper that is used when -D_FORTIFY_SOURCE
is used.
Fixes: #176.

Provide wrapper for fortified version of readlinkat.

---

src/libumockdev-preload.c

Without this, we call the local readlink function, which will go
through the "WRAP3" version of readlink.
It generally avoids having the UMOCKDEV_PATH doubly appended,
so its mostly harmless from that point of view, but when
'-fno-semantic-interposition' and _FORTIFY_SOURCE are enabled during
compilation,  there's the potential for the wrapper functions to get
complex enough not to be inlineable, even though they are marked as
always_inline, resulting in a compile error.

Call libc's `readlink` directly in get_rdev

---

packit.yaml

- `specfile_path` searches the tree for a .spec, and thus should be
able to find it in packaging/ by itself.
- `files_to_sync` already defaults to syncing the packit YAML and the
spec, but this was broken for a few days
(https://github.com/packit/packit/issues/1525)

packit: Drop obsolete fields

---

src/libumockdev-preload.c
src/umockdev.vala

Revert commit 4b1ab11c244a0a488bb. Merely setting
`$SYSTEMD_DEVICE_VERIFY_SYSFS` does not work for GI bindings. Instead,
wrap fstatfs() and mangle the type to SYSFS_MAGIC if the path points
into our mocked /sys. This satisfies udev.
Fixes https://github.com/systemd/systemd/issues/23499

preload: Wrap fstatfs()

---

meson.build
src/umockdev-ioctl.vala
tests/test-umockdev.py

So, things are not usable from python. Thing still broken:
* We need the old _ref/_unref functions for API compatibility if we use a GObject, not sure how to do that. Or can we use a boxed type?
* The length of data is not tagged in the GIR
So, kinda works, but you can't actually read the memory. And, not sure if maybe a `ctypes.memmove` shouldn't be workable instead.
The bindings cannot deal with a struct object, as it is not a boxed type
and it'll try to ref/unref using g_object_ref. Probably this is
fixable in another way, but this works.
Also, the python bindings cannot modify the byte data directly, so add
an update method that is essentially a glorified memcpy.

ioctl: Make data object usable from python

---

meson.build

See https://fedoraproject.org/wiki/Changes/PortingToModernC

Move to gnu11 C standard, fail on old C constructs

---

packaging/umockdev.spec
tests/test-umockdev-run.vala

Many koji architectures are emulated, especially in Pagure/packit builds. Don't be too picky about the timing there, similar to what we do in Debian autopkgtest.

spec: Be generous with slow test timeouts

---

src/umockdev.vala

Set the env variable before starting the worker thread, to ensure that it sees it.
Fixes #206

umockdev: Fix race with worker thread accessing $UMOCKDEV_DIR

---

tests/test-umockdev-run.vala

Closes #208
Testing fails with
cannot remove /tmp/.X11-unix/X5: No such file or directory
Fixes: 0f686e11540c ("Check FileUtils.{remove,unlink}() return code")

test: Allow missing .X11-unix/X5 file

---

src/libumockdev-preload.c

Never read the udev cache data from the system, as this might make properties of system devices leak through our mocked udev, such as headsets showing up as internal devices.
Closes: https://github.com/martinpitt/umockdev/issues/213

preload: Don't read udev cache data from system

---

tests/test-umockdev.c

This ensures that the emulated /dev (which is created in `g_get_tmp_dir()` via `DirUtils.make_tmp()` and the feature check are done in the same directory. If `$TMPDIR` is set, that may not be the case.
Fixes #217

test: Use g_get_tmp_dir()

---

README.md
meson.build
src/selinux.vapi
src/umockdev-record.vala
src/umockdev.vala
tests/run-nix
tests/test-umockdev-record.vala
tests/test-umockdev-run.vala
tests/test-umockdev-vala.vala

If libselinux is available, record the original node SELinux context into an internal `__DEVCONTEXT` property, and restore it in `umockdev-run`. This property can also be set via the API.
Fixes #220

Record and restore SELinux context for mocked /dev nodes

---

src/libumockdev-preload.c

musl has both of these functions (though not the separate "64" variants that glibc).
Thanks to Alyssa Ross @alyssais for finding this and the initial patch!
---
This is an alternative to #224 which doesn't rip apart the fstatfs{,64} and statfs{,64} declarations.
Closes #224

preload: wrap fstatfs() and statfs() on musl

---

meson.build
meson_options.txt
src/umockdev-record.vala
tests/run-gentoo

meson 1.4 stopped hiding valac's warnings [1], which fails compilation
due to our `-Werror=` settings. There's not much that we can do at this
point, so stop making them non-fatal.
This reverts the `gentoo-hacks` option from commit 539af0b4f36. Turns
out that this wasn't a compiler change in Gentoo after all, but that
Gentoo backported [2] that meson change at that time.
Many thanks to Dominique Leuenberger @DimStar77 for tracking down the
root cause!
Fixes #228
[1] https://github.com/mesonbuild/meson/commit/5f659af870011e
[2] https://github.com/gentoo/gentoo/pull/34141

Make vala C code errors non-fatal

---

tests/run-nix

Fixes https://github.com/martinpitt/umockdev/issues/230

tests: Update Nix dependencies

---

meson.build
src/glibc.vapi
tests/test-umockdev-vala.vala

Calling Ioctl.USBDEVFS_REAPURB in the test causes a SIGBUS error on sparc64. It's actually surprising that this test passes on a lot of architectures -- the pcap file was recorded on x86_64, and there may be some unaligned access there.
I don't know enough about compilers, alignment, and pcap files to actually fix this. But the more pressing issue is to fix the package build on sparc64.
Fixes #218

Skip usbfs_ioctl_pcap on sparc64

---

src/libumockdev-preload.c

__USE_TIME_BITS64 is now always defined on 64 bit architectures, but the `__clock_gettime64` redirect doesn't exist there.
See https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=a4ed0471d7

preload: Fix time64 redirect for glibc 2.39.9

---

src/libumockdev-preload.c

glibc 2.38 in Debian doesn't know about `__USE_TIME64_REDIRECTS` yet, so no redirection took place. Curiously this only broke on Debian/Ubuntu ARM architectures, nowhere else.
Apply some guesswork to define `__USE_TIME64_REDIRECTS` ourselves in the right circumstances.

preload: Re-fix time64 redirects for glibc < 2.39.9

---

packit.yaml

While they are not directly related to building srpms, this caused the koji-build jobs to run twice, and thus creating confusing "Fedora Koji build failed to be triggered" issues.
Fixes #245

packit: Restrict koji_build and bodhi_update to Fedora

---

src/libumockdev-preload.c

Related to and discussed more at https://github.com/martinpitt/umockdev/issues/252
---
To avoid clobbering a threads signal mask with that of another thread, take locks before storing a thread's signal mask in case another thread has already stored its own signal mask in the trap_path_sig_restore variable, but has not yet restored it.
Without this change, the following could happen:
If umockdev-run is used to run a process which spawns multiple threads, and each of those threads writes to a file, and has specific signal mask requirements, the following may happen
- Thread A: 
- store thread A's sigmask in trap_path_sig_restore and block all signals for thread A 
- acquire trap_path_lock
- Thread B: 
- store thread B's sigmask in trap_path_sig_restore and block all signals for thread B. …

preload: fix sigmask block and restore race

---

src/uevent_sender.c

This error was already being handled on the `connect` call right above these changes, but wasn't being handled on the call to `sendmsg`. Depending on the timing it was possible for the `connect` call to succeed while the `sendmsg` call failed with an ECONNREFUSED error leading to the test crashing from the abort call.

Handle spurious "connection refused" when sending a uevent

---

tests/test-umockdev-record.vala

/sys/fs/selinux might exist, yet the checked path might have no
context defined.
Drop the check for the selinux pseudo-fs, and check the eventual
errno if lgetfilecon() fails.
On ENODATA (context doesn't exist, or the process can't access it),
ENOTSUP (extended attributes not supported/disabled) and ENOSYS
(lgetxattr syscall used by lgetfilecon() not available), ensure
__DEVCONTEXT is not there and continue.
On every other error, fail the test case as before.

 tests: umockdev-record: t_system_single: handle missing SELinux context on /dev/null

---

tests/run-gentoo

About a month ago, vala fell out of umockdev's build dependencies. Explicitly install it.
----
@thesamesam @mattst88: Do you happen to know why [valac does not get installed any more](https://github.com/martinpitt/umockdev/actions/runs/11624155887/job/32372326306)? It used to be part of 
```
ACCEPT_KEYWORDS="~*" emerge dev-util/umockdev --with-test-deps --onlydeps --getbinpkg
```
in the [run-gentoo test script](https://github.com/martinpitt/umockdev/blob/main/tests/run-gentoo#L23), but that doesn't happen any more. This was introduced by @mattst88 in ed29c0107ead81c1e460fff3884 and basically unchanged since then, other than the binary package optimization in commit 6a1d57a80a511c.
I can hack around it like in this PR by installing it explicitly, but that feels bad -- vala very much needs …

tests: Hack Gentoo build

---

src/umockdev.vala
tests/test-umockdev.c

Fixes #247
This is mostly in a "this train ride ends here" state, but it works, and isn't too horrible. It could still use some fine-tuning, documentation, etc. @mkemlogic you weren't too happy about the names, we can do some bikeshedding :wink: 
What do you think?

Add umockdev_testbed_wait_script(), add API to add scripts/evemu as strings

---

src/ioctl_tree.c
src/ioctl_tree.vapi
src/umockdev-ioctl.vala
tests/test-ioctl-tree.c
tests/test-umockdev-vala.vala

The umockdev-vala testcase randomly fails on some platforms (hppa, sparc64, powerpc, see:[1][2][3]) because the ioctl() testcase checks the return value pointed to by "ret" in ioctl_tree_execute() which might have stale data as it wasn't initialized.
Fix it by properly initializing the return code.
Additionally force all code paths to provide a valid return code address.
Tested on hppa-linux and armhf-linux.
[1] https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=hppa&ver=0.19.0-1&stamp=1735373270&raw=0
[2] https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=powerpc&ver=0.19.0-1&stamp=1735375553&raw=0
[3] https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=sparc64&ver=0.19.0-1&stamp=1735380455&raw=0

Fix ioctl_tree_execute() ret type and initialization

---

tests/test-umockdev-vala.vala

The class IoctlSpiBase (see src/umockdev-spi.vala) has a comment that it only works on 64bit platforms.
Disable those tests on 32-bit platforms for now.
This fixes my tests on the (32-bit) hppa platform.
This patch is just to show the problem (and a possible workaround).
If you find another way to fix (or skip) this test I'm fine with that,
Thanks!
Helge

tests: Disable spidev on big-endian 32-bit platforms

---

src/ioctl.vapi
src/libumockdev-preload.c
src/valgrind.supp
tests/test-umockdev-vala.vala

Don't invoke the remote ioctl handler for host devices. This fixes e.g.
ioctls on /dev/tty or other standard devices which the tested program
may want to do.
This bug was hidden by the conditional check in t_usbfs_ioctl_static()
which skipped the check if /dev/tty wasn't accessible -- which is the
case in `meson test`. Move to a FIONREAD ioctl on /dev/stdout, which
works on ttys and pipes, i.e. everywhere. Make that check unconditional.

preload: Only emulate ioctls on emulated devices

---

packit.yaml

https://issues.redhat.com/browse/TFT-2612 got fixed long ago.

packit: Re-enable CentOS 10 integration tests

---

tests/test-umockdev-vala.vala

The `0xdeadbeef` constant in Vala is implicitly an int64. On 32 bit big-endian architectures like powerpc this argument vanishes during its interpretation through varargs and long (i.e. gets shifted to the second argument, which we never look at). Explicitly make it an int.
---
This fixes the [Debian powerpc build failure](https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=powerpc&ver=0.19.1-2&stamp=1736005171&raw=0).
@hdeller FYI, as you were looking into FTBFS on other architectures. This is the last one, I debugged/validated this on `perotto` (Debian porter box).

tests: Fix ioctl data type

---

src/libumockdev-preload.c

This is specific to Debian armhf (Fedora does not do it that way).
----
Fixes [Debian build failure](https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=armhf&ver=0.19.2-1&stamp=1753901783&raw=0)

preload: Wrap `__fstat64_time64()`
