martinpitt/umockdev

- src/libumockdev-preload.c
`ls -l` now uses this, which causes confusing error messages.
> preload: Wrap [l]getxattr()

- .travis.yml
To enable the corresponding test cases.
> travis: Add gphoto test dependency

- src/libumockdev-preload.c
- tests/test-umockdev.c
A quick proof-of-concept to mitigate issue #69 
It unbreaks the fwupd thunderbolt test for me by trapping the relevant openat64 call:
```
testbed wrapped open64(/) -> /
testbed wrapped openat64 (sys) -> /tmp/umockdev.9S6CDZ/sys
testbed wrapped openat64 (devices) -> devices
testbed wrapped openat64 (domain0) -> domain0
testbed wrapped openat64 (0-0) -> 0-0
testbed wrapped openat64 (0-1) -> 0-1
testbed wrapped openat64 (0-2) -> 0-2
```
This is just WIP and might need cleanup.
> Wrap openat{,64} to accommodate for libudev changes

- src/ioctl_tree.c
Compiles on armhf, aarch64 and x86_64.
Related to #83
> Fix compilation error on armhf

- src/umockdev.vala
- tests/test-umockdev.c
This implements creating symlinks for S: lines in umockdev device files.
> Implement TODO for devnode symlinks

- src/libumockdev-preload.c
When e.g. using libgusb (GLib libusb wrapper) libusb has its mainloop
running in one thread while the main thread might be submitting urbs
directly using another ioctl. This can cause the wrong URB to be
returned.
Fix this issue by adding locking to ioctl_emulate.
> Add locking to ioctl emulation

- src/umockdev.vala
- tests/test-umockdev-record.vala
- tests/test-umockdev-run.vala
- tests/test-umockdev.c
this includes several commits to stop some of the flakiest test cases that cause lots of autopkgtest false failures on armhf (and occasionally on other archs)
> Fix flaky test operations

- src/umockdev.vala
Handle EOF on the control pipe. This sometimes seems to happen in slow
test environments even though neither end of the control pipe got
closed.
Now close them properly, and use the EOF event as notification instead
of this.running and sending a control byte.
Fixes #105
> Fix SocketServer control EOF handling

- src/ioctl_tree.c
Sorry! Turns out I did not test this enough …
----
Commit 95470c488bf0 ("ioctl-tree: Add function to query size of passed
structure") added a way to query the expected data size. Unfortunately,
we do not have an entry for URB submission, meaning that the data would
simply never be resolved.
Fix this by adding a new I_DUMMY entry without any functions that will
be ignored during execution.
> ioctl-tree: Fix USB submit URB data resolution

- src/umockdev-pcap.vala
This fixes discard (which I had apparently not tested really).
Another thing is that it adds some debug print if replay is stuck unexpectedly. That shouldn't happen normally, but could if the application has a large timeout and there is a buffer mismatch.
> Fix discard and print messages on stuck replay

- src/ioctl.vapi
- src/umockdev-pcap.vala
Stupid error in assert.
Also, looking at the code, I realised that control transfer playback cannot work right now. But, I am not sure what it should look like and don't have a good test case right now unfortunately (I hope to get some samples soon, if I do, it should be a quick fix).
> Fix pcap replayer

- src/umockdev-pcap.vala
Control transfer replaying was not quite working. The primary reason was
that setup data needs to be compared differently from other buffer data.
Also, the code would incorrectly skip control transfers when there were
no reapable urbs.
> pcap: Implement control transfer replaying

- meson.build
This allows users to easily disable -Werror if necessary.
> Use werror project option

- .packit.yaml
- packaging/umockdev.spec
> Add testing through packit

- meson.build
- src/libumockdev-preload.c
- tests/test-umockdev.c
> Wrap fstatat()

- tests/test-umockdev-vala.vala
> tests: Fix /umockdev-testbed-vala/detects_running_outside_testbed

- src/umockdev.vala
- tests/test-umockdev.c
We were sending the `add` uevent before setting up the binary/link
attributes and setting up the device node, which causes race conditions
in consumers.
To fix that, introduce an internal `add_devicev_no_uevent()` method which does
everything from testbed_add_devicev() except sending the uevent. Use 
that new helper from both that function and add_from_string() after everything
is ready.
Fixes #173
> Fix uevent race condition in add_from_string()

- src/libumockdev-preload.c
- tests/test-umockdev.c
https://github.com/martinpitt/umockdev/pull/187#issuecomment-1140963786
> statfs() follow-ups

- src/libumockdev-preload.c
Having signals enabled while holding a lock is messy as certain
recursions may occur. As such, disable signals before taking the mutex
and release signals again afterwards.
> preload: Disable signals before locking

- src/getversion.sh
> getversion.sh: Fix git check

- .github/workflows/tests.yml
- meson.build
- src/libumockdev-preload.c
- tests/run-dnf
- tests/test-static-code
- tests/test-umockdev.c
Fixes compatibility with systemd 258
(https://github.com/systemd/systemd/issues/38392).
Fixes #271
> systemd 258 compatibility
